name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install uv
        run: pip install uv

      - name: Create and activate virtual environment
        run: |
          uv venv
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install .

      - name: Fetch people.js
        run: |
          curl -H "Authorization: token ${{ secrets.REPO_RW_PAT }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o people.js \
               https://raw.githubusercontent.com/ebmdatalab/team-manual/refs/heads/main/team-map/people.js

      - name: Update locations
        run: python src/cli.py update-locations --source-file people.js

      - name: Check for location changes
        id: check_location_changes
        run: |
          if git diff --exit-code locations_config.json; then
            echo "No changes detected in locations_config.json"
            echo "locations_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in locations_config.json"
            echo "locations_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit location changes
        if: steps.check_location_changes.outputs.locations_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add locations_config.json
          git commit -m "Update locations_config.json"
          git push

      - name: Update routes
        run: python src/cli.py update-routes

      - name: Check for route changes
        id: check_route_changes
        run: |
          if git diff --exit-code routes.json; then
            echo "No changes detected in routes.json"
            echo "routes_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in routes.json"
            echo "routes_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit route changes
        if: steps.check_route_changes.outputs.routes_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add routes.json
          git commit -m "Update routes.json"
          git push

      - name: Build embedded HTML
        run: python src/cli.py build-html

      - name: Check for HTML changes
        id: check_html_changes
        run: |
          if git diff --exit-code index_embedded.html; then
            echo "No changes detected in index_embedded.html"
            echo "::set-output name=html_changed::false"
          else
            echo "Changes detected in index_embedded.html"
            echo "::set-output name=html_changed::true"
          fi

      - name: Commit HTML changes
        if: steps.check_html_changes.outputs.html_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index_embedded.html
          git commit -m "Update index_embedded.html"
          git push
