name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch people.js
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3.raw" \
             -o people.js \
             https://raw.githubusercontent.com/ebmdatalab/team-manual/refs/heads/main/team-map/people.js

    - name: Update locations
      run: python src/cli.py update-locations --source-file people.js

    - name: Check for location changes
      id: check_location_changes
      run: |
        if git diff --exit-code locations_config.json; then
          echo "No changes detected in locations_config.json"
          echo "::set-output name=locations_changed::false"
        else
          echo "Changes detected in locations_config.json"
          echo "::set-output name=locations_changed::true"
        fi

    - name: Commit location changes
      if: steps.check_location_changes.outputs.locations_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add locations_config.json
        git commit -m "Update locations_config.json"
        git push

    - name: Update routes
      run: python src/cli.py update-routes

    - name: Check for route changes
      id: check_route_changes
      run: |
        if git diff --exit-code routes.json; then
          echo "No changes detected in routes.json"
          echo "::set-output name=routes_changed::false"
        else
          echo "Changes detected in routes.json"
          echo "::set-output name=routes_changed::true"
        fi

    - name: Commit route changes
      if: steps.check_route_changes.outputs.routes_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add routes.json
        git commit -m "Update routes.json"
        git push

    - name: Build embedded HTML
      run: python src/cli.py build-html

    - name: Check for HTML changes
      id: check_html_changes
      run: |
        if git diff --exit-code index_embedded.html; then
          echo "No changes detected in index_embedded.html"
          echo "::set-output name=html_changed::false"
        else
          echo "Changes detected in index_embedded.html"
          echo "::set-output name=html_changed::true"
        fi

    - name: Commit HTML changes
      if: steps.check_html_changes.outputs.html_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index_embedded.html
        git commit -m "Update index_embedded.html"
        git push

    - name: Create Release
      if: steps.check_changes.outputs.changed == 'true'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}-${{ github.sha }}
        release_name: Release ${{ github.ref }}-${{ github.sha }}
        body: |
          Automated release for updated index_embedded.html
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: steps.check_changes.outputs.changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./index_embedded.html
        asset_name: index_embedded.html
        asset_content_type: text/html
